name = "openai-cf-hg"# todo
main = "index.js"
compatibility_date = "2024-11-11"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-hg-images"
preview_bucket_name = "ai-hg-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "" # replace with your own.
MODEL_MAPPER = { "gpt-4o-mini" = "meta-llama/Llama-3.1-8B-Instruct" } # Optional

[observability.logs]
enabled = true
# head_sampling_rate = 1 # optional. default = 1.
invocation_logs = true

[placement]
mode = "smart"